#%%
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 


""" 7 """

#pd.concat
# df.concat
# ignore_index 
# df.append 
# multiindex -> fetch 
# concat dataframes horizontally 


courses = pd.read_csv("dataset_2/courses.csv")
deliveries = pd.read_csv("dataset_2/deliveries.csv")
matches = pd.read_csv("dataset_2/matches.csv")
month_1 = pd.read_csv("dataset_2/reg-month1.csv")
month_2 = pd.read_csv("dataset_2/reg-month2.csv")
students = pd.read_csv("dataset_2/students.csv")
matches = pd.read_csv("dataset_2/matches.csv")




#%%
#::::::::::::--Concat--:::::::::::::::
# pd.concat : means vertical and horizontal data add 
# print(courses,deliveries,matches,month_1,month_2,month_3)

#:::::::::::: 1. Vertical dataframes concate 
# there should be same numbers of column  
# month_1.shape

regs = pd.concat([month_1,month_2],ignore_index=True)


##::::::::::: 2. Multiindex DataFrame using concatination

multi = pd.concat([month_1,month_2],keys=['Month_1','Month_2'])
multi

multi.loc[('Month_1',0)]

##:::::::::::: 3. Horizontally daatframe addition 

# hori = pd.concat([month_1,month_2],axis=1)

# hori.iloc[0].values[0]


##:::::::::::::---- Mergeing(Joining) ---:::::::::::::::::::::::

#%%
regs
students

#:::: 1. inner Join

# only common data will be displayed
# students.merge(regs,how='inner',on='student_id')

# :::::: 2. Left Join 
# on the basis of courses(left table) all data will be shown
# courses.merge(regs,how='left',on='course_id')

# ::::: 3. Right Join

# right table data will be displayed(which is not in the left table NaN will be shown)
# temp_stud = pd.DataFrame({
#      'student_id':[26,27,28],
#      'name':['Dev','Devesh','Devendra'],
#      'partener':[28,26,27]
# })

# students = pd.concat([temp_stud,students],ignore_index=True)

# students.head()

# courses.merge(regs,how='right',on='course_id')

# students.merge(regs,how='right',on='student_id')

##::::::::: 4. Outer join 

# every data will be displayed from both tables irrespective of id data is present or not in a table   
# print(students)
# print(regs)
# data = students.merge(regs,how='outer',on='student_id')
# print(data)


#%%
#:::::::::::: Questions on the topic 

# Que1 :: Total Revenue Generated

# pd.concat([students,courses,regs],ignore_index=True)

total = regs.merge(courses,how="inner",on='course_id')['price'].sum()

total

# Month by month revenue generated by the company 

months = pd.concat([month_1,month_2],keys=['month_1','month_2']).reset_index() # making a combined dataframe
months.merge(courses,on='course_id').groupby('level_0')['price'].sum().sum()

# Que 3. Print the registration table 
# cols -> name -> course -> price

students.merge(regs,on='student_id').merge(courses,on='course_id')[['name','course_name','price']].sum()
regs.merge(students,on='student_id').merge(courses,on='course_id')[['name','course_name','price']].sum()


# Que: 4 Plot bar chart for revenue/course 

# regs.merge(courses,on='course_id').groupby('course_name')['price'].sum().plot(kind='bar')

# 5. Find students who enrolled in both the months 

common_stud_id = np.intersect1d(month_1['student_id'],month_2['student_id'])
common_stud_id

students[students['student_id'].isin(common_stud_id)]

#%%

# Find course that get no enrollment 

# courses['course_id']
# courses['course_id']

course_id_list = np.setdiff1d(courses['course_id'],regs['course_id'])

courses[courses['course_id'].isin(course_id_list)]

# Find the students who did not enroll into any courses 

student_id_list = np.setdiff1d(students['student_id'],regs['student_id'])
students[students['student_id'].isin(student_id_list)].shape[0]

# Print student name -> partner name for all enrolled students 

# Here we will use 'self join' 

students.merge(students,how='inner',left_on='partner',right_on='student_id')


# Que Find top 3 students who did most number of enrolls 

tp = regs.merge(students,on='student_id').groupby(['student_id','name'])['name'].count().sort_values(ascending=False)

# print(tp)

## Que Find top 3 students who spend most amount of money on courses

most_spend = regs.merge(students,on='student_id').merge(courses,on='course_id').groupby(['student_id','name'])['price'].sum().sort_values(ascending=False)

most_spend


#%%
# The ipl wala dataset 

# problem 
# Find top 3 stadium with highest sixes/match ration
# find orange cap holder of all the seasons 

matches

temp_data = deliveries.merge(matches,left_on='match_id',right_on='id')

six_df = temp_data[temp_data['batsman_runs'] == 6]


# stdium with the number of sixes

num_six = six_df.groupby('venue')['venue'].count()

num_matches = matches['venue'].value_counts()
# num_matches
(num_six/num_matches).sort_values(ascending=False).head(5)

print(f'Number of Matches : {num_matches}',f'number of sixes {num_six}')


# Find Orange cap holder 

# find the batsman who has scored the most runs in a season 

# use merged data 

temp_data.groupby(['season','batsman'])['batsman_runs'].sum().reset_index().sort_values('batsman_runs',ascending=False).drop_duplicates('season',keep='first').sort_values('season',ascending=True)






# %%
